pub fn run() -> utils::error::Result<()> {
    // For demo purposes, just return an error
    Err(utils::error::Error::new("Simulated error"))
}
