pub fn run() -> utils::error::Result<()> {
    core::commands::simulate_error()
}
